-- drop FK
ALTER TABLE books DROP CONSTRAINT IF EXISTS FK_BOOKS_AUTHOR;
ALTER TABLE books DROP CONSTRAINT IF EXISTS FK_BOOKS_PUBLICATION;

-- drop pk
ALTER TABLE books DROP CONSTRAINT IF EXISTS PK_BOOKS;
ALTER TABLE authors DROP CONSTRAINT IF EXISTS PK_AUTHORS;
ALTER TABLE publications DROP CONSTRAINT IF EXISTS PK_PUBLICATIONS;

-- create PK
ALTER TABLE books ADD CONSTRAINT PK_BOOKS PRIMARY KEY (id);
ALTER TABLE authors ADD CONSTRAINT PK_AUTHORS PRIMARY KEY (id);
ALTER TABLE publications ADD CONSTRAINT PK_PUBLICATIONS PRIMARY KEY (id);

-- create FK
ALTER TABLE books ADD CONSTRAINT FK_BOOKS_AUTHOR
        FOREIGN KEY (author_id) REFERENCES authors(id);
ALTER TABLE books ADD CONSTRAINT FK_BOOKS_PUBLICATION
        FOREIGN KEY (publication_id) REFERENCES publications(id);





